apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cas-ms-api-docs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-ibmstg"
